### ISSUE TITLE
ISIN as input to  `bdp()` fetches NA incorrectly: (ISINs unsupported?)

### ISSUE THREAD

**Issue by danielkrizian** [johnlaing/blpwrapper#1]
Some securities defined as ISIN return `NA` values from `bdp()` function where they should return some values. This is the case for approx one third of my ~500 strong ISIN list.

As an example, `US5949181045` returns proper value (`"Common Stock"`), but only if it is appended with `"Equity"`, while other variants fail, including sample `CA91911K1021` (which should return `"Common Stock"` too):

``` R
> conn = blpConnect(throw.ticker.error=F)
R version 3.1.0 (2014-04-10) 
rJava Version 0.9-4 
Rbbg Version 0.5.3 
Java environment initialized successfully.
Looking for most recent blpapi3.jar file...
Adding C:\blp\API\APIv3\JavaAPI\v3.6.1.0\lib\blpapi3.jar to Java classpath
Bloomberg API Version 3.6.1.0 
> 
> bdp(conn, securities="US5949181045",fields="SECURITY_TYP2")
             SECURITY_TYP2
US5949181045          <NA>
> 
> bdp(conn, securities="US5949181045 Equity",fields="SECURITY_TYP2")
                    SECURITY_TYP2
US5949181045 Equity  Common Stock
> 
> bdp(conn, securities="US5949181045 ISIN",fields="SECURITY_TYP2")
                  SECURITY_TYP2
US5949181045 ISIN          <NA>
> 
> bdp(conn, securities="CA91911K1021",fields="SECURITY_TYP2")
                    SECURITY_TYP2
CA91911K1021 Equity          <NA>
>
> bdp(conn, securities="CA91911K1021 Equity",fields="SECURITY_TYP2")
                    SECURITY_TYP2
CA91911K1021 Equity          <NA>
> bdp(conn, securities="CA91911K1021 ISIN",fields="SECURITY_TYP2")
                  SECURITY_TYP2
CA91911K1021 ISIN          <NA>

```

Running demo directly on Java API (on Windows: `Start-> Bloomberg-> API Data Demo`) :
![image](https://cloud.githubusercontent.com/assets/2865860/4150742/58dc3202-3440-11e4-8b78-8e8aadee2955.png)

works and returns:

```
ReferenceDataResponse = {
    securityData[] = {
        securityData = {
            security = "/Isin/CA91911K1021"
            eidData[] = {
            }
            fieldExceptions[] = {
            }
            sequenceNumber = 0
            fieldData = {
                SECURITY_TYP2 = "Common Stock"
            }
        }
    }
}
```

As well as running Excel API:
`=BDP("CA91911K1021 ISIN","SECURITY_TYP2")` # returns "Common Stock"

Cursory test with other fields yielded same behavior.

Are ISINs supported in `Rbbg` ?

**Comment by johnlaing** [comment]
To be clear, that is only returning NA because you've set throw.ticker.errors=FALSE. Otherwise that specification would throw a ticker error advising of an invalid security.

Nevertheless this is very interesting. I've always been under the impression that all securities had to include their corresponding "yellow key", e.g. Equity. I've never seen the "foobar123 ISIN" form before. And indeed, that doesn't work as-is in Rbbg, which means it also doesn't work as-is in the underlying Java API. As often happens Bloomberg is manipulating the request behind the scenes, and not being especially transparent about what they're doing.

But the response in your example is suggestive. If we take that form of the security "/ISIN/foobar123" it works!

```
> bdp(conn, "/ISIN/US5949181045", "SECURITY_TYP2")
                   SECURITY_TYP2
/ISIN/US5949181045  Common Stock
```

So there you have it.

**Comment by danielkrizian** [comment]
Thank you. Indeed "foobar123 ISIN" is the standard format, as is "barfoo321 BBGID":

``` R
> bdp(conn, securities="/ISIN/US5949181045",fields="ID_BB_GLOBAL")
                   ID_BB_GLOBAL
/ISIN/US5949181045 BBG000BPH459
> bdp(conn, securities="/BBGID/BBG000BPH459",fields="SECURITY_TYP2")
                    SECURITY_TYP2
/BBGID/BBG000BPH459  Common Stock
```

which is equivalent to `=BDP("BBG000BPH459 BBGID", "SECURITY_TYP2")`
